# =============================================================================
# gestion_projet ? Application Properties
# Fichier en UTF-8
# =============================================================================
spring.application.name=gestion_projet

# -----------------------------------------------------------------------------
# Encodage HTTP
# -----------------------------------------------------------------------------
server.port=8070
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# =============================================================================
# DATABASE CONFIG (PostgreSQL)
# =============================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_projet
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================================================
# JPA / HIBERNATE
# =============================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# =============================================================================
# MAIL CONFIG (Gmail SMTP)
# =============================================================================
app.mail.enabled=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zouaghimariem91@gmail.com
spring.mail.password=iqfd hnag hkbf wvma
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# =============================================================================
# LOGS
# =============================================================================
logging.level.root=INFO
logging.level.tn.uib.bnpl.gestion_projet=INFO
logging.level.org.springframework.security=DEBUG